### PR TITLE
README - say "has been discontinued."

### PR DESCRIPTION
**Pull request by paulvi**
Please also update/remove link above code

### CODE REVIEW

**Comment by paulvi** [comment]
o..

give a link to https://github.com/groovy/GMavenPlus

**Comment by jdillon** [comment]
the project is not discontinued, the gmaven-plus project is unrelated separate implementation of similar functionality.

version 1 of this plugin however is no longer being developed, version 2 however is still recommended to folks who need a simple means to add groovy scripting to maven builds.

**Comment by paulvi** [comment]
This issue is about making it clear for new users at README and URL above code.

Also if you know how, to give the information at http://www.mojohaus.org/plugins.html

**Comment by jdillon** [comment]
gmaven was not discontinued; v2 re-purposed to focus on script execution due to various complexities of trying to manage compilation which is better done by the groovy-eclipse-compiler.

**Pull request closed without merging**
